### PR TITLE
Update pico_private_conf.php

### PR DESCRIPTION
**Pull request by kicsihobi**

### CODE REVIEW

**Comment by jbleuzen** [comment]
Is this necessary ? 
The array is already declared global in `pico_private.php`, so I don't see why it should be global here...

**Comment by kicsihobi** [comment]
This gave me a bit of a headache too... http://php.net/manual/en/function.include.php : When a file is included, the code it contains inherits the variable scope of the line on which the include occurs. Any variables available at that line in the calling file will be available within the called file, from that point forward. However, all functions and classes defined in the included file have the global scope.

Since the conf file is not included in the actual functional file, the variables declared in it will be in the scope of the function (lib/pico.php:load_plugins()) that it is included in, they will be local to that function, so they cannot be referenced with global modifier later.

**Comment by jbleuzen** [comment]
Ok, yeah it's something I'm not very confortable either… Thanks for your explanations :+1: 
I merge it then…

**Comment by kicsihobi** [comment]
Thanks to you for the plugin!

**Pull request merged**
